Home Task 2
tdmnew/NodeJSGlobalMentoringProgram pull request #3
Opened 2021-10-25 11:58 UTC by tdmnew

- Added express routing
- Added validation for each route

@Dmitry-White please let me know if the eslint and tsconfig looks okay to you - I've tried to use the config provided, and added a few rules here. `max-len` was commented out after seeing the post on our Teams channel.

Thanks!

2021-10-27 11:18 UTC, Dmitry-White requested changes
Looks amazing!
Only a couple of minor pending changes and we're good to merge!

2021-10-27 11:18 UTC, Dmitry-White commented on src/controllers/login.controller.ts
> +  } else {
I suppose there's no need for "else" wrapper here, since Node.js preferred approach is "early return" anyway.
Consider going through the app and applying this "early return" instead of "if-else" chain where possible.

2021-10-27 11:18 UTC, Dmitry-White commented on src/controllers/users.controller.ts
> +  let user: User | undefined = data.find((user) => user.id === id);
Consider going through the app and changing "let" to "const" where possible.
"const" has a small but important semantic meaning - it shows that the variable does not change anywhere in the code, therefore it is considered best practice to default to "const" at all times.

2021-10-27 11:18 UTC, Dmitry-White commented on src/db/index.ts
> +export let data: User[] = [];
It would be amazing to align all the imports to one particular export style.
Since you're using "export default" in some places, my suggestion would be to stick to "export default" when it's only one thing that needs to be exported from a file and use named exports in other cases.
Also, it would be good to bring all the exports down to the bottom of a file instead of doing inline exports - again, to align with export default approach.

2021-10-30 15:53 UTC, tdmnew commented on src/controllers/login.controller.ts
> +  } else {
That makes sense - I thought I had an issue with early return for some of the controllers but I was mistaken.

I've had to include `else` for `updateUser` and `deleteUser` due to `Object is potentially undefined` TypeScript complains - hope that's okay?

2021-10-30 15:58 UTC, tdmnew commented on src/controllers/users.controller.ts
> +  let user: User | undefined = data.find((user) => user.id === id);
Ah, I was likely mistaken here - I thought I should use `let` for things that are mutable like the users 'database', but saying that TypeScript would have given complains for using `const` for things like this (Which it didn't). This has been changed :)

2021-10-30 15:59 UTC, tdmnew commented on src/db/index.ts
> +export let data: User[] = [];
That's fair - I was pretty inconsistent in the use of default imports. Where possible, I've changed these to be default.

2021-11-01 12:12 UTC, Dmitry-White approved these changes

2021-11-02 19:09 UTC, merged